# Generated by Django 5.2.1 on 2025-05-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Cabinet',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='department',
            new_name='cabinet',
        ),
    ]
