# Generated by Django 5.2.1 on 2025-09-16 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cartitem_date_time_cartitem_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cartitem'),
        ),
    ]
