# Generated by Django 5.2.1 on 2025-09-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('description', models.TextField(verbose_name='Описание')),
                ('founded', models.DateField(verbose_name='Дата основания')),
                ('employees', models.PositiveIntegerField(verbose_name='Количество сотрудников')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Логотип')),
                ('video_url', models.URLField(blank=True, verbose_name='Видео о компании')),
                ('history', models.TextField(blank=True, verbose_name='История по годам')),
                ('requisites', models.TextField(blank=True, verbose_name='Реквизиты')),
                ('certificate', models.TextField(blank=True, verbose_name='Сертификат')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
    ]
